name: CI API DRIVN-COOK

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installe Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Installe les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Vérifie la compilation TS
      - name: Build project
        run: npm run build

      # 5. Lance les tests Vitest
      - name: Run tests
        run: npm run test
